name: Secret Scan
on:
  pull_request:
    paths:
      - "**/*"
jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for secrets (regex demo)
        run: python src/secret_scan.py
